In [1]:
import numpy as np
a=np.array([0,1,2,4])
print(a)

[0 1 2 4]


In [2]:
b=np.array([[1,2,3,4],[6,7,8,9]])
print(b)

[[1 2 3 4]
 [6 7 8 9]]


In [8]:
c=np.arange(0,31,5)
print(c)

[ 0  5 10 15 20 25 30]


In [7]:
d=np.linspace(0,10,9)
print(d)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [10]:
e=np.zeros((1,10))
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
e=np.ones((1,5))
print(e)

[[1. 1. 1. 1. 1.]]


In [12]:
f=np.random.random((5,5))
print(f)

[[0.68324016 0.62883546 0.38877526 0.19321494 0.55298766]
 [0.77287782 0.14836188 0.92396491 0.33286538 0.98028253]
 [0.0369596  0.16116906 0.82377827 0.31488952 0.18474924]
 [0.24036698 0.12886313 0.70278749 0.52892673 0.21649882]
 [0.66542206 0.82651593 0.78641939 0.35981417 0.58474722]]
