In [1]:
import numpy as np
a=np.array([1,3,4,2])
print(a)

[1 3 4 2]


In [2]:
a.shape

(4,)

In [4]:
a.size

4

In [3]:
a.ndim

1

In [6]:
a=np.array([1,2,3])
b=np.array([4,8,9])
print(a-b)
print(a+b)
print(a*b)

[-3 -6 -6]
[ 5 10 12]
[ 4 16 27]


In [7]:
a=np.array([10.3,10.4,3])
np.abs(a)

array([10.3, 10.4,  3. ])

In [8]:
np.ones(4)


array([1., 1., 1., 1.])

In [10]:
a=np.array([1,4,7,8])
np.sum(a)
np.max(a)
np.mean(a)
np.min(a)
np.median(a)

5.5

In [11]:
np.arange(0,20,3)
a

array([1, 4, 7, 8])

In [19]:
a=np.array([8,7,7,8,9])
np.unique(a)

array([7, 8, 9])

In [21]:
np.random.randint(0,10,10)


array([2, 1, 2, 0, 0, 8, 8, 0, 2, 7])

In [36]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [3]:
import numpy as np
a=np.zeros[3,2]

NameError: name 'np' is not defined